imports:
    - { resource: ../default/config.yml }
    - { resource: parameters.yml }

chaplean_unit:
    cache_sqlite_db: true

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   '%database_driver%'
                path:     '%kernel.cache_dir%/test.db'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8
                server_version: 5.6
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true
