Chaplean\Bundle\UnitBundle\Entity\Client:
    properties:
        name: <lastname()>
        code: <current()>ABC
        email: client<current()>.<email()>
        dateAdd: <(new \DateTime('-2 hours'))>

Chaplean\Bundle\UnitBundle\Entity\Product:
    properties:
        name: <firstname()>

Chaplean\Bundle\UnitBundle\Entity\Provider:
    properties:
        name: <firstname()>

Chaplean\Bundle\UnitBundle\Entity\User:
    properties:
        email: <email()>
        status: @status-[active, inactive, deleted]