parameters:
    doctrine.dbal.connection_factory.class: Chaplean\Bundle\UnitBundle\Utility\MultipleTestDatabaseConnectionFactory

services:
    _defaults:
        autowire: true
        public: true

    Chaplean\Bundle\UnitBundle\EventListener\TestSessionListener:
        tags:
            - { name: 'kernel.event_subscriber' }