version: '3.3'
services:
    application:
        container_name: unit_bundle_app
        build: .
        volumes:
            - .:/var/www/symfony:delegated
            - ~/.composer:/root/.composer:delegated
            - ~/.ssh:/root/.ssh:delegated
        links:
            - mysql:mysql
    mysql:
        container_name: unit_bundle_mysql
        image: chaplean/mysql:mariadb10.1
        volumes:
            - mysql_data:/var/lib/mysql:rw
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: app_user
            MYSQL_PASSWORD: app_password
            MYSQL_DATABASE: test_database
networks: {}
volumes:
    mysql_data: ~
