imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: '@ChapleanMailerBundle/Resources/config/config.yml' }

framework:
    test: ~
    translator:      { fallback: '%locale%' }
    secret:          '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    default_locale:  '%locale%'
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        storage_id: session.storage.mock_file
    fragments:       ~
    http_method_override: true
    profiler:
        collect: false

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   '%database_driver%'
                host:     '%database_host%'
                port:     '%database_port%'
#                dbname:   '%database_name%'
                path:   '%database_name%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8
                server_version: 5.6
            logging: null
            profiling: null
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    spool:
        type: file

# Chapleanmailer Configuration
chaplean_mailer:
    sender_address: 'staff@chaplean.coop'
    sender_name: 'Chaplean'
    subject:
        prefix: '[TEST]'
    test: true

fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    serializer:
        serialize_null: true
